config/routes.rb
Rails.application.routes.draw do

  get 'upload' => 'images#new', :as => 'upload'
  get 'images/create'
  get 'images/destroy'
  get 'images/index'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/show'

  resources :images, :categories

  root 'images#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :category

    mount_uploader :image, ImageUploader

    before_save :update_image_attributes

    private
        def update_image_attributes
            if image.present? && image_changed?
                self.image_content_type = image.file.content_type
                self.image_file_size = image.file.size
            end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :getCategoryNav

    private
    def getCategoryNav
      @categoryNav = Category.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created"
      redirect_to images_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = "Category Updated"
      redirect_to category_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      flash[:notice] = "Image Created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    flash[:notice] = "Image Deleted"
    redirect_to images_path

  end

  def index
    @images = Image.all
    @categories = Category.all
  end

  private
    def image_params
      params.require(:image).permit(:image, :category_id, :image_title, :image_description, :image_file_size, :image_content_type,:remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
    <!-- Check for errors -->
    <% if @category.errors.any? %>
        <% @category.errors.full_messages.each do |msg| %>
            <!-- Show errors -->
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, class: 'form-control' %><br />
    </div>

    <%= f.submit "Submit", class: 'btn btn-dark' %>
    <%= link_to "Cancel", category_path(params[:id]), class: 'btn btn-dark' %>
<% end %>
<br>
<h4 class="page-header">Images in <%= @category.name %></h4>
<div id="edit_images">
    <% if @images.exists? %>
        <% @images.each_slice(6) do |image| %>
            <div class="row">
                <% image.each do |image| %>
                    <div class="col-md-2">
                        <%= image_tag image.image_url(:thumb) %>
                        <center><%= link_to "Delete", image_path(image), class: 'delete', method: :delete, data: {confirm: 'Are you sure?'} %> </center>
                    </div>
                <% end %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
    <!-- Check for errors -->
    <% if @category.errors.any? %>
        <% @category.errors.full_messages.each do |msg| %>
            <!-- Show errors -->
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, class: 'form-control' %><br />
    </div>

    <%= f.submit "Submit", class: 'btn btn-dark' %>
    <%= link_to "Cancel", root_path, class: 'btn btn-dark' %>
<% end %>

app/views/categories/show.html.erb
<div id="gallery">
  <h1><%= @category.name %> <%= link_to "Edit", edit_category_path, class: "float-right btn btn-warning" %> </h1>

  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
      <div class="row">

        <% image.each do |image| %>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= image.image_title %></div>
                  <div class="line"></div>
                  <div class="desc"><%= image.image_description %></div>
                </div>
                <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag image.image_url(:thumb) %></div>
            </div>
          </div>
        <% end %>

      </div>
    <% end %>
  <% else %>
    <p>Upload some images smarthead! </p>
  <% end %>
</div>

app/views/images/index.html.erb
<div id="gallery">
  <h1>All images</h1>

  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
      <div class="row">

        <% image.each do |image| %>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= image.image_title %></div>
                  <div class="line"></div>
                  <div class="desc"><%= image.image_description %></div>
                </div>
                <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag image.image_url(:thumb) %></div>
            </div>
          </div>
        <% end %>

      </div>
    <% end %>
  <% else %>
    <p>Upload some images smarthead! </p>
  <% end %>

  
</div>

app/views/images/new.html.erb
<h2>Upload Image</h2>

<%= form_for @image, :html => {:multipart => true} do |f| %>
    <!-- Check for errors -->
    <% if @image.errors.any? %>
        <% @image.errors.full_messages.each do |msg| %>
            <!-- Show errors -->
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <div class="form-group">
        <%= f.label :image_title %><br />
        <%= f.text_field :image_title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"}, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :image_description %>
        <%= f.text_area :image_description, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>


    <br>

    <%= f.submit "Submit", class: 'btn btn-dark' %>
    <%= link_to "Cancel", images_path, class: 'btn btn-dark' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Gallery</a>
      
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link #{'active' if params[:controller] == 'images'}"%>
          </li>
          
          <% @categoryNav.each do |category| %>
            <li>
              <%= link_to category.name, category_path(category.id), class: "nav-link" %>
            </li>
          <% end %>
        
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Upload", upload_path, class: "nav-link"%></li>
          <li class="nav-item"><%= link_to "Add Category", new_category_path, class: "nav-link"%></li>
        </ul>

      </div>
    </nav>

    <section>
      <div class="container">

        <!-- Alerts & Messages -->
        <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice] %> </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert] %> </div>
        <% end %>
        
        <%= yield %>
        
      </div>
    </section>



    <footer>
      <p>Copyright &copy; 2019, Gallery</p>
    </footer>


  </body>
</html>